# -*- coding: utf-8 -*-
import re
import glob
import os
import shutil

lst = [u"Kareem Abdul-Jabbar",
u"Shaquille O'Neal",
u"Kobe Bryant ^",
u"Kevin Garnett ^",
u"Michael Jordan *",
u"Karl Malone *",
u"Jerry West *",
u"Wilt Chamberlain *",
u"Bob Cousy *",
u"Tim Duncan ^",
u"John Havlicek *",
u"Larry Bird *",
u"Elvin Hayes *",
u"Magic Johnson *",
u"Moses Malone *",
u"Hakeem Olajuwon *",
u"Oscar Robertson *",
u"Bill Russell *",
u"Dolph Schayes *",
u"Isiah Thomas *",
u"Charles Barkley *",
u"Elgin Baylor *",
u"Julius Erving *",
u"Patrick Ewing *",
u"Allen Iverson",
u"Dirk Nowitzki ^",
u"Bob Pettit *",
u"Ray Allen ^",
u"Paul Arizin *",
u"Clyde Drexler *",
u"Hal Greer *",
u"Jason Kidd ^",
u"Paul Pierce ^",
u"David Robinson *",
u"John Stockton *",
u"George Gervin *",
u"Robert Parish *",
u"Gary Payton",
u"Lenny Wilkens *",
u"Dominique Wilkins *",
u"Rick Barry *",
u"Vince Carter ^",
u"Dave DeBusschere *",
u"Alex English *",
u"Larry Foust",
u"LeBron James ^",
u"Bob Lanier *",
u"Dikembe Mutombo",
u"Steve Nash ^",
u"Bill Sharman *",
u"Dwyane Wade ^",
u"Yao Ming",
u"Dave Bing *",
u"Chris Bosh ^",
u"Dave Cowens *",
u"Walt Frazier *",
u"Harry Gallatin *",
u"Grant Hill ^",
u"Jerry Lucas *",
u"Ed Macauley *",
u"Slater Martin *",
u"Tracy McGrady ^",
u"Dick McGuire *",
u"Kevin McHale *",
u"Alonzo Mourning",
u"Scottie Pippen *",
u"Willis Reed *",
u"Jack Sikma",
u"Nate Thurmond *",
u"Chet Walker",
u"Jo Jo White",
u"James Worthy *",
u"Nate Archibald *",
u"Larry Costello",
u"Adrian Dantley *",
u"Walter Davis",
u"Joe Dumars *",
u"Artis Gilmore *",
u"Richie Guerin",
u"Tom Heinsohn *",
u"Dwight Howard ^",
u"Bailey Howell *",
u"Lou Hudson",
u"Joe Johnson ^",
u"Neil Johnston *",
u"Shawn Kemp",
u"Vern Mikkelsen *",
u"Jermaine O'Neal ^",
u"Mitch Richmond",
u"Amar'e Stoudemire ^",
u"Jack Twyman *",
u"George Yardley *",
u"Carmelo Anthony ^",
u"Chauncey Billups ^",
u"Carl Braun",
u"Brad Daugherty",
u"Wayne Embry",
u"Tom Gola *",
u"Gail Goodrich *",
u"Cliff Hagan *",
u"Tim Hardaway",
u"Dennis Johnson *",
u"Gus Johnson *",
u"Marques Johnson",
u"Sam Jones *",
u"Rudy LaRusso",
u"Pete Maravich *",
u"Bob McAdoo *",
u"Reggie Miller",
u"Sidney Moncrief",
u"Chris Mullin *",
u"Don Ohl",
u"Chris Paul ^",
u"Andy Phillip *",
u"Gene Shue",
u"Rudy Tomjanovich",
u"Wes Unseld *",
u"Bobby Wanzer *",
u"Chris Webber",
u"Paul Westphal",
u"Vin Baker",
u"Walt Bellamy *",
u"Otis Birdsong",
u"Rolando Blackman",
u"Tom Chambers",
u"Maurice Cheeks",
u"Doug Collins",
u"Billy Cunningham *",
u"Bob Dandridge",
u"Bob Davies *",
u"Dick Garmaker",
u"Pau Gasol ^",
u"Johnny Green",
u"Penny Hardaway",
u"Connie Hawkins *",
u"Spencer Haywood",
u"Mel Hutchins",
u"Bobby Jones",
u"Bernard King",
u"Bill Laimbeer",
u"Maurice Lucas",
u"Shawn Marion ^",
u"George Mikan *",
u"Earl Monroe *",
u"Willie Naulls",
u"Tony Parker ^",
u"Jim Pollard *",
u"Mark Price",
u"Micheal Ray Richards...",
u"Arnie Risen *",
u"Alvin Robertson",
u"Guy Rodgers",
u"Ralph Sampson",
u"Latrell Sprewell",
u"David Thompson *",
u"Ben Wallace ^",
u"Rasheed Wallace",
u"Sidney Wicks",
u"Mark Aguirre",
u"Gilbert Arenas ^",
u"Bill Bridges",
u"Phil Chenier",
u"Terry Dischinger",
u"Kevin Durant ^",
u"Steve Francis",
u"Richard Hamilton ^",
u"Kevin Johnson",
u"Eddie Jones",
u"Bob Kauffman",
u"Johnny Kerr",
u"Bob Love",
u"Clyde Lovellette *",
u"Dan Majerle",
u"George McGinnis",
u"Jeff Mullins",
u"Larry Nance",
u"Glen Rice",
u"Rajon Rondo ^",
u"Derrick Rose ^",
u"Dan Roundfield",
u"Brandon Roy",
u"Detlef Schrempf",
u"Charlie Scott",
u"Paul Seymour",
u"Peja Stojaković",
u"Maurice Stokes *",
u"Dick Van Arsdale",
u"Tom Van Arsdale",
u"Norm Van Lier",
u"Antoine Walker",
u"Jamaal Wilkes",
u"Buck Williams",
u"Deron Williams ^",
u"Leo Barnhorst",
u"Zelmo Beaty",
u"Carlos Boozer ^",
u"Elton Brand ^",
u"Terrell Brandon",
u"Frank Brian",
u"Caron Butler ^",
u"Joe Caldwell",
u"Archie Clark",
u"Terry Cummings",
u"Baron Davis ^",
u"John Drew",
u"Kevin Duckworth",
u"Walter Dukes",
u"Dike Eddleman",
u"Sean Elliott",
u"Michael Finley",
u"Joe Fulks *",
u"Jack George",
u"Manu Ginóbili ^",
u"Blake Griffin ^",
u"Al Horford ^",
u"Allan Houston",
u"Rod Hundley",
u"Žydrūnas Ilgauskas",
u"Antawn Jamison ^",
u"Eddie Johnson",
u"John Johnson",
u"Larry Johnson",
u"Larry Kenon",
u"Don Kojis",
u"Fat Lever",
u"Rashard Lewis ^",
u"Kevin Love ^",
u"Jeff Malone",
u"Danny Manning",
u"Stephon Marbury",
u"Jack Marin",
u"Brad Miller ^",
u"Norm Nixon",
u"Jim Paxson",
u"Geoff Petrie",
u"Terry Porter",
u"Glenn Robinson",
u"Truck Robinson",
u"Red Rocha",
u"Dennis Rodman *",
u"Fred Scolari",
u"Ken Sears",
u"Frank Selvy",
u"Paul Silas",
u"Jerry Sloan",
u"Phil Smith",
u"Randy Smith",
u"Jerry Stackhouse ^",
u"Reggie Theus",
u"Andrew Toney",
u"Kelly Tripucka",
u"Kiki Vandeweghe",
u"Jimmy Walker",
u"Bill Walton *",
u"David West ^",
u"Russell Westbrook ^",
u"Gus Williams",
u"Brian Winters",
u"Shareef Abdur-Rahim",
u"Alvan Adams",
u"Michael Adams",
u"Danny Ainge",
u"LaMarcus Aldridge ^",
u"Kenny Anderson",
u"B. J. Armstrong",
u"Don Barksdale",
u"Dick Barnett",
u"Dana Barros",
u"Butch Beard",
u"Ralph Beard",
u"Mookie Blaylock",
u"John Block",
u"Bob Boozer",
u"Vince Boryla",
u"Bill Bradley *",
u"Fred Brown",
u"Don Buse",
u"Andrew Bynum ^",
u"Austin Carr",
u"Joe Barry Carroll",
u"Bill Cartwright",
u"Sam Cassell",
u"Cedric Ceballos",
u"Len Chappell",
u"Nathaniel Clifton",
u"Derrick Coleman",
u"Jack Coleman",
u"Antonio Davis",
u"Dale Davis",
u"Luol Deng ^",
u"Vlade Divac",
u"James Donaldson",
u"Mark Eaton",
u"Dale Ellis",
u"Ray Felix",
u"Sleepy Floyd",
u"World B. Free",
u"Billy Gabor",
u"Marc Gasol ^",
u"Chris Gatling",
u"Danny Granger ^",
u"Horace Grant",
u"A. C. Green",
u"Rickey Green",
u"Alex Groza",
u"Tom Gugliotta",
u"Devin Harris ^",
u"Bob Harrison",
u"Hersey Hawkins",
u"Walt Hazzard",
u"Roy Hibbert ^",
u"Tyrone Hill",
u"Lionel Hollins",
u"Jeff Hornacek",
u"Josh Howard ^",
u"Juwan Howard ^",
u"Andre Iguodala ^",
u"Darrall Imhoff",
u"Dan Issel *",
u"Lucious Jackson",
u"Mark Jackson",
u"Steve Johnson",
u"Chris Kaman ^",
u"Jim King",
u"Andrei Kirilenko",
u"Billy Knight",
u"Sam Lacey",
u"Christian Laettner",
u"Clyde Lee",
u"David Lee ^",
u"Reggie Lewis",
u"Jamaal Magloire ^",
u"Kenyon Martin ^",
u"Jamal Mashburn",
u"Anthony Mason",
u"Xavier McDaniel",
u"Antonio McDyess",
u"Jon McGlocklin",
u"Tom Meschery",
u"Eddie Miles",
u"Mike Mitchell",
u"Steve Mix",
u"Calvin Murphy *",
u"Calvin Natt",
u"Jameer Nelson ^",
u"Chuck Noble",
u"Charles Oakley",
u"Mehmet Okur ^",
u"Ricky Pierce",
u"Jim Price",
u"Zach Randolph ^",
u"Theo Ratliff",
u"Michael Redd ^",
u"Richie Regan",
u"Doc Rivers",
u"Clifford Robinson",
u"Flynn Robinson",
u"Curtis Rowe",
u"Jeff Ruland",
u"Bob Rule",
u"Campy Russell",
u"Cazzie Russell",
u"Woody Sauldsberry",
u"Fred Schaus",
u"Lee Shaffer",
u"Lonnie Shelton",
u"Adrian Smith",
u"Steve Smith",
u"Rik Smits",
u"John Starks",
u"Don Sunderlage",
u"Wally Szczerbiak",
u"Otis Thorpe",
u"Nick Van Exel",
u"Gerald Wallace ^",
u"Paul Walther",
u"Kermit Washington",
u"Scott Wedman",
u"Jayson Williams",
u"Mo Williams ^",
u"Kevin Willis",
u"Metta World Peace ^",
u"Max Zaslofsky"]
fileFormattedPlayers = []
fileFormattedFileNames = []
allStars = []
for player in lst:
    charTrimmed = re.sub('[!@#$^*]', '', player)
    spaceTrimmed = charTrimmed.strip()
    fileFormatted = re.sub(r'\W+', '_', spaceTrimmed)
    fileFormattedPlayers.append(fileFormatted.encode('ascii','ignore') + ".csv")


for fName in glob.glob('/Users/rahulmatta/Desktop/EECS 349/NBA_HOF/NBA_DATA_CLEAN/*'):
    fileFormattedFileNames.append(os.path.basename(fName))


for f in fileFormattedFileNames:
    if (f in fileFormattedPlayers):
        shutil.move("/Users/rahulmatta/Desktop/EECS 349/NBA_HOF/NBA_DATA_CLEAN/"+ f, "/Users/rahulmatta/Desktop/EECS 349/NBA_HOF/NBA_DATA_CLEAN_ALL_STARS_ONLY/"+f)



